{
  "openapi": "3.0.0",
  "info": {
    "title": "E-commerce API",
    "description": "API de e-commerce para gerenciamento de usuários, autenticação e operações relacionadas.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/api",
      "description": "Servidor local"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "paths": {
    "/auth/signup": {
      "post": {
        "summary": "Sign up",
        "tags": ["Auth"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Tux Linux"
                  },
                  "email": {
                    "type": "string",
                    "example": "tuxlinux@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "senha123"
                  }
                },
                "required": ["name", "email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User registered successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Tux Linux",
                  "email": "tuxlinux@example.com"
                }
              }
            }
          },
          "400": {
            "description": "User already exists"
          }
        }
      }
    },

    "/auth/login": {
      "post": {
        "summary": "Login",
        "tags": ["Auth"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "tuxlinux@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "senha123"
                  }
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "example": {
                  "user": {
                    "id": 1,
                    "name": "Tux Linux",
                    "email": "tuxlinux@example.com"
                  },
                  "token": "jwt-token-here"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect password"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },

    "/auth/me": {
      "get": {
        "summary": "Get authenticated user data",
        "tags": ["Auth"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authenticated user data",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Tux Linux",
                  "email": "tuxlinux@example.com"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/users": {
      "get": {
        "summary": "List users with pagination - (Admin)",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer",
              "example": 1
            },
            "description": "Page number to be returned (starting from 1)"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer",
              "example": 10
            },
            "description": "Maximum number of users to be returned per page"
          }
        ],
        "responses": {
          "200": {
            "description": "List of users",
            "content": {
              "application/json": {
                "example": {
                  "users": [
                    {
                      "id": 1,
                      "name": "Tux Linux",
                      "email": "tuxlinux@example.com"
                    },
                    {
                      "id": 2,
                      "name": "Tux User",
                      "email": "tuxuser@example.com"
                    }
                  ],
                  "total": 20,
                  "page": 1,
                  "limit": 10
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "summary": "Update user information",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": true
              },
              "example": {
                "Field": "Value"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Tux Linux",
                  "email": "tuxlinux@example.com"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/users/{id}": {
      "get": {
        "summary": "Get a user by ID - (Admin)",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User data",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Tux Linux",
                  "email": "tuxlinux@example.com"
                }
              }
            }
          },
          "404": {
            "description": "User not found"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/users/{id}/role": {
      "put": {
        "summary": "Change user role - (Admin)",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "role": {
                    "type": "string",
                    "example": "ADMIN"
                  }
                },
                "required": ["role"]
              },
              "example": {
                "role": "ADMIN"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User role changed successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "role": "ADMIN"
                }
              }
            }
          },
          "404": {
            "description": "User not found"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/users/address/{id}": {
      "delete": {
        "summary": "Delete an address by ID",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Address deleted successfully"
          },
          "404": {
            "description": "Address not found"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/users/address": {
      "get": {
        "summary": "List all addresses for authenticated user",
        "tags": ["User"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of addresses",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "lineOne": "Rua Exemplo, 456",
                    "lineTwo": "Apto 101",
                    "city": "Cidade Exemplo",
                    "country": "Brasil",
                    "postalCode": "00000-000",
                    "userId": 1
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },

    "/products": {
      "post": {
        "summary": "Criar um novo produto",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Produto Exemplo"
                  },
                  "description": {
                    "type": "string",
                    "example": "Produto Exemplo"
                  },
                  "price": {
                    "type": "number",
                    "example": 99.99
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "example": ["tag1", "tag2"]
                  }
                },
                "required": ["name", "price", "tags"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Produto criado com sucesso",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Produto Exemplo",
                  "price": 99.99,
                  "tags": "tag1,tag2"
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      },
      "get": {
        "summary": "Listar produtos",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "skip",
            "in": "query",
            "schema": {
              "type": "integer",
              "example": 0
            },
            "description": "Número de resultados a pular"
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de produtos",
            "content": {
              "application/json": {
                "example": {
                  "count": 2,
                  "data": [
                    {
                      "id": 1,
                      "name": "Produto Exemplo",
                      "price": 99.99,
                      "tags": "tag1,tag2"
                    },
                    {
                      "id": 2,
                      "name": "Outro Produto",
                      "price": 199.99,
                      "tags": "tag3,tag4"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      }
    },
    "/products/multiple": {
      "post": {
        "summary": "Criar múltiplos produtos",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "example": "Produto Exemplo"
                    },
                    "price": {
                      "type": "number",
                      "example": 99.99
                    },
                    "tags": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "example": ["tag1", "tag2"]
                    }
                  },
                  "required": ["name", "price", "tags"]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Produtos criados com sucesso",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "name": "Produto 1",
                    "price": 99.99,
                    "tags": "tag1,tag2"
                  },
                  {
                    "id": 2,
                    "name": "Produto 2",
                    "price": 199.99,
                    "tags": "tag3,tag4"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "summary": "Atualizar um produto",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Produto Atualizado"
                  },
                  "price": {
                    "type": "number",
                    "example": 149.99
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "example": ["tag5", "tag6"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Produto atualizado com sucesso",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Produto Atualizado",
                  "price": 149.99,
                  "tags": "tag5,tag6"
                }
              }
            }
          },
          "404": {
            "description": "Produto não encontrado"
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      },
      "delete": {
        "summary": "Deletar um produto",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Produto deletado com sucesso",
            "content": {
              "application/json": {
                "example": {
                  "message": "Product deleted"
                }
              }
            }
          },
          "404": {
            "description": "Produto não encontrado"
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      },
      "get": {
        "summary": "Obter um produto por ID",
        "tags": ["Product"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Produto encontrado",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Produto Exemplo",
                  "price": 99.99,
                  "tags": "tag1,tag2"
                }
              }
            }
          },
          "404": {
            "description": "Produto não encontrado"
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      }
    },
    "/cart": {
      "post": {
        "summary": "Add item to cart",
        "tags": ["Cart"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddCartItem"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Item added to cart successfully"
          },
          "404": {
            "description": "Product not found"
          },
          "403": {
            "description": "Unauthorized access"
          }
        }
      },
      "get": {
        "summary": "Get cart items",
        "tags": ["Cart"],
        "responses": {
          "200": {
            "description": "Cart items retrieved successfully"
          },
          "404": {
            "description": "Cart is empty"
          }
        }
      }
    },
    "/cart/{id}": {
      "delete": {
        "summary": "Delete item from cart",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cart item deleted"
          },
          "404": {
            "description": "Cart item not found"
          },
          "403": {
            "description": "Unauthorized to delete this cart item"
          }
        }
      },
      "put": {
        "summary": "Change item quantity in cart",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangeQuantity"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Cart item quantity updated"
          },
          "404": {
            "description": "Cart item not found"
          },
          "403": {
            "description": "Unauthorized access"
          }
        }
      }
    },
    "/orders": {
      "post": {
        "summary": "Create an order",
        "tags": ["Order"],
        "responses": {
          "200": {
            "description": "Order created successfully"
          },
          "404": {
            "description": "Cart is empty or address not found"
          }
        }
      },
      "get": {
        "summary": "List user orders",
        "tags": ["Order"],
        "responses": {
          "200": {
            "description": "User orders retrieved"
          },
          "404": {
            "description": "No orders found"
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "summary": "Get order by ID",
        "tags": ["Order"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order details retrieved"
          },
          "404": {
            "description": "Order not found"
          }
        }
      },
      "put": {
        "summary": "Cancel an order",
        "tags": ["Order"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order cancelled successfully"
          },
          "400": {
            "description": "Order is already cancelled"
          },
          "404": {
            "description": "Order not found"
          }
        }
      }
    },
    "/orders/index": {
      "get": {
        "summary": "List all orders (Admin)",
        "tags": ["Order"],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Orders retrieved"
          }
        }
      }
    },
    "/orders/{id}/status": {
      "get": {
        "summary": "Change order status (Admin)",
        "tags": ["Order"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangeOrderStatus"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Order status updated"
          },
          "404": {
            "description": "Order not found"
          }
        }
      }
    }
  }
}
